# Copy this file to .github/workflows/terraform.yml in any repository
# that needs Terraform automation

name: Terraform

on:
  push:
    branches: [ main, master ]
    paths:
      - '**.tf'
      - '.github/workflows/terraform.yml'
  pull_request:
    branches: [ main, master ]
    paths:
      - '**.tf'
      - '.github/workflows/terraform.yml'
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write
  id-token: write

jobs:
  terraform:
    uses: sansritiishwar/simple-workflow/.github/workflows/reusable-terraform.yml@main
    with:
      terraform_version: 'latest'
      working_directory: '.'
    secrets: inherit
